// <auto-generated />
using System;
using Challenge_Clyvo_NET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Challenge_Clyvo_NET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524041105_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO_ANIMAL");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESPECIE");

                    b.Property<int>("Idade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_ANIMAL");

                    b.Property<double>("Peso")
                        .HasPrecision(4, 2)
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("PESO");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RACA");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SEXO");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("T_NET_ANIMAL", (string)null);
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_AGENDAMENTO");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CONSULTA");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("T_NET_CONSULTA", (string)null);
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONTATO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL_CONTATO");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUM_CONTATO");

                    b.Property<int>("PessoaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PESSOA");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("T_NET_CONTATO", (string)null);
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PESSOA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_PESSOA");

                    b.HasKey("Id");

                    b.ToTable("T_NET_PESSOA", (string)null);
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ENDERECO");

                    b.Property<int>("PessoaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PESSOA");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("T_NET_RESPONSAVEL", (string)null);
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Veterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESPECIALIDADE");

                    b.Property<int>("PessoaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PESSOA");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("T_NET_VETERINARIO", (string)null);
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Animal", b =>
                {
                    b.HasOne("Challenge_Clyvo_NET.Models.Responsavel", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Consulta", b =>
                {
                    b.HasOne("Challenge_Clyvo_NET.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Challenge_Clyvo_NET.Models.Veterinario", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Contato", b =>
                {
                    b.HasOne("Challenge_Clyvo_NET.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Responsavel", b =>
                {
                    b.HasOne("Challenge_Clyvo_NET.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Challenge_Clyvo_NET.Models.Veterinario", b =>
                {
                    b.HasOne("Challenge_Clyvo_NET.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
